// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwOXWPA8TBeBFHtkJdaRVq_izMWTBrh20',
    appId: '1:533886226292:web:de200dc39d9535afd36621',
    messagingSenderId: '533886226292',
    projectId: 'jbtailors-72459',
    authDomain: 'jbtailors-72459.firebaseapp.com',
    storageBucket: 'jbtailors-72459.appspot.com',
    measurementId: 'G-NBWTG1BZHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoCJRV_COHvG5bJ9WArpc8U3AaRRB24Z0',
    appId: '1:533886226292:android:9f1eb00c448e61a4d36621',
    messagingSenderId: '533886226292',
    projectId: 'jbtailors-72459',
    storageBucket: 'jbtailors-72459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuehoNt862gr1umCKFe-bw9FxyMhX4iFM',
    appId: '1:533886226292:ios:0a59375d11b95f2fd36621',
    messagingSenderId: '533886226292',
    projectId: 'jbtailors-72459',
    storageBucket: 'jbtailors-72459.appspot.com',
    iosClientId: '533886226292-m5j2or833relhdjnnff4p6hhus2627ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.jbTailor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuehoNt862gr1umCKFe-bw9FxyMhX4iFM',
    appId: '1:533886226292:ios:0a59375d11b95f2fd36621',
    messagingSenderId: '533886226292',
    projectId: 'jbtailors-72459',
    storageBucket: 'jbtailors-72459.appspot.com',
    iosClientId: '533886226292-m5j2or833relhdjnnff4p6hhus2627ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.jbTailor',
  );
}
